# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         ''
url:                 https://bockstaller.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Lukas Bockstaller
  url:               https://twitter.com/lbockstaller
  email:             lukas.bockstaller@posteo.de

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0

